### ISSUE TITLE
Multiple drives created on 64GB SD card - undocumented

### ISSUE THREAD

**Issue by SteveALee** [WOA-Project/WOA-Deployer-Rpi#43]
** Description **
I'm not sure if this is expected but  there is no documentation on the expected results. Could you add docs of expected output?

G: EIFSP boot partion
H: blank and had to format it 128MB
J: Windows image

**To Reproduce**
* I have a 64GB card formated to Fat32 as required for a Raspberry Pi
* Loaded as G:
* install.wim mounted as I:
* Run WoA deployer
* Get asked to format H:

**Expected behavior**

Unknown as not documented

Thanks

**Comment by lukajin** [comment]
This is normal. These partitions are:
1. EFI System partition - Used for system boot loaders. Usually 100MB.
2. MSR - Microsoft Reserved partition. It has no format and you shouldn't format it. It has some special uses (Google for more info), but it's usually unnecessary. Usually 128MB.
3. The main system partition. Contains the Windows itself and its data (The C: drive). Usually covers the rest of the drive.

The standard Windows installation creates all these 3 as well, unless you partition the drive manually. The EFI partition usually has no drive letter and the MSR partition is hidden from Windows Disk Management completely, but can be seen in diskpart. It's not hidden on a SD card, probably because Microsoft didn't expect you to use a SD as a main disk drive. You should just ignore it.
